services:
  db:
    image: postgres:15-alpine
    container_name: vitrineclick-db
    environment:
      POSTGRES_DB: vitrineclick
      POSTGRES_USER: vitrine_admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
